### ISSUE TITLE
DBM error

### ISSUE THREAD

**Issue by tskisner** [healpy/pysm#31]
Using master branch, with a conda-forge python3.6 stack and running the toast unit tests I get:
```
Traceback (most recent call last):
  File "/home/kisner/software/toast/lib/python3.6/site-packages/toast/tests/ops_sim_pysm.py", line 192, in test_op_pysm_nosmooth
    units="uK_RJ",
  File "/home/kisner/software/toast/lib/python3.6/site-packages/toast/timing.py", line 43, in df
    return f(*args, **kwargs)
  File "/home/kisner/software/toast/lib/python3.6/site-packages/toast/todmap/sim_det_pysm.py", line 141, in __init__
    map_dist=map_dist,
  File "/home/kisner/software/toast/lib/python3.6/site-packages/toast/todmap/pysm.py", line 76, in __init__
    if init_sky
  File "/home/kisner/software/toast/lib/python3.6/site-packages/toast/timing.py", line 43, in df
    return f(*args, **kwargs)
  File "/home/kisner/software/toast/lib/python3.6/site-packages/toast/todmap/pysm.py", line 124, in init_sky
    output_unit=self._units,
  File "/home/kisner/software/cmbenv/cmbenv_aux/lib/python3.6/site-packages/pysm-3.0.0-py3.6.egg/pysm/sky.py", line 101, in __init__
    component_config, nside=nside, map_dist=map_dist
  File "/home/kisner/software/cmbenv/cmbenv_aux/lib/python3.6/site-packages/pysm-3.0.0-py3.6.egg/pysm/sky.py", line 37, in create_components_from_config
    map_dist=map_dist
  File "/home/kisner/software/cmbenv/cmbenv_aux/lib/python3.6/site-packages/pysm-3.0.0-py3.6.egg/pysm/models/spdust.py", line 53, in __init__
    self.I_ref = self.read_map(map_I, unit=unit_I)
  File "/home/kisner/software/cmbenv/cmbenv_aux/lib/python3.6/site-packages/pysm-3.0.0-py3.6.egg/pysm/models/template.py", line 65, in read_map
    dataurl=self.dataurl,
  File "/home/kisner/software/cmbenv/cmbenv_aux/lib/python3.6/site-packages/pysm-3.0.0-py3.6.egg/pysm/models/template.py", line 200, in read_map
    filename = data.get_pkg_data_filename(path)
  File "/home/kisner/software/cmbenv/cmbenv_python/lib/python3.6/site-packages/astropy/utils/data.py", line 588, in get_pkg_data_filename
    timeout=remote_timeout)
  File "/home/kisner/software/cmbenv/cmbenv_python/lib/python3.6/site-packages/astropy/utils/data.py", line 1012, in download_file
    with shelve.open(urlmapfn) as url2hash:
  File "/home/kisner/software/cmbenv/cmbenv_python/lib/python3.6/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/home/kisner/software/cmbenv/cmbenv_python/lib/python3.6/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/home/kisner/software/cmbenv/cmbenv_python/lib/python3.6/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
```
Is the dbm format python version dependent?  Installing the "gdbm" package did not help.

**Comment by zonca** [comment]
I don't know, it seems an `astropy` issue, not specific to PySM.

I would try to remove your `.astropy` folder, you might have created the url cache file with some other version of python that changed the type of `dbm`?

**Comment by tskisner** [comment]
Indeed, doing
```
rm -rf ~/.astropy
```
solved the problem.
